# Generated by Django 2.1.4 on 2018-12-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
